# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=64)),
                ('staff_name_kana', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('女', 'Female'), ('男', 'Male')], max_length=2)),
                ('birth_day', models.DateField()),
                ('mail_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('post_code', models.IntegerField(verbose_name=7)),
                ('address', models.CharField(max_length=255)),
                ('e_name', models.CharField(max_length=64)),
                ('e_relationship', models.CharField(max_length=10)),
                ('e_phone_number', models.CharField(max_length=10)),
                ('join_day', models.CharField(choices=[('設営日', '0day'), ('三日目', '3day'), ('一日目', '1day'), ('二日目', '2day')], max_length=5)),
                ('assignment_1', models.SmallIntegerField(verbose_name=3)),
                ('assignment_2', models.PositiveIntegerField(null=True, verbose_name=3)),
                ('partner', models.CharField(max_length=64, null=True)),
                ('parking', models.CharField(choices=[('使用しない', 'No'), ('使用する', 'Yes')], max_length=10)),
                ('hotel', models.CharField(choices=[('使用しない', 'No'), ('使用する', 'Yes')], max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('memo', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
