# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_data',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='join_day',
            field=models.CharField(choices=[('三日目', '3day'), ('設営日', '0day'), ('二日目', '2day'), ('一日目', '1day')], max_length=5),
        ),
    ]
