# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0002_auto_20170825_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_data',
            name='assignment_1',
            field=models.CharField(choices=[('east2', '東2ホール'), ('east6', '東6ホール'), ('east4', '東5ホール'), ('east1', '東1ホール'), ('east8', '東8ホール'), ('east3', '東3ホール'), ('east3', '東4ホール'), ('east7', '東7ホール')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='assignment_2',
            field=models.CharField(choices=[('east2', '東2ホール'), ('east6', '東6ホール'), ('east4', '東5ホール'), ('east1', '東1ホール'), ('east8', '東8ホール'), ('east3', '東3ホール'), ('east3', '東4ホール'), ('east7', '東7ホール')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='gender',
            field=models.CharField(choices=[('Male', '男'), ('Female', '女')], max_length=2),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='hotel',
            field=models.CharField(choices=[('Yes', '使用する'), ('No', '使用しない')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='join_day',
            field=models.CharField(choices=[('0day', '設営日'), ('1day', '一日目'), ('3day', '三日目'), ('2day', '二日目')], max_length=5),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='mail_address',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='parking',
            field=models.CharField(choices=[('Yes', '使用する'), ('No', '使用しない')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff_data',
            name='post_code',
            field=models.CharField(max_length=7),
        ),
    ]
