# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0003_auto_20170825_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=64)),
                ('staff_name_kana', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Female', '女'), ('Male', '男')], max_length=2)),
                ('birth_day', models.DateField()),
                ('mail_address', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=255)),
                ('e_name', models.CharField(max_length=64)),
                ('e_relationship', models.CharField(max_length=10)),
                ('e_phone_number', models.CharField(max_length=10)),
                ('join_day', models.CharField(choices=[('0day', '設営日'), ('1day', '一日目'), ('2day', '二日目'), ('3day', '三日目')], max_length=5)),
                ('assignment_1', models.CharField(choices=[('east8', '東8ホール'), ('east2', '東2ホール'), ('east3', '東3ホール'), ('east4', '東5ホール'), ('east3', '東4ホール'), ('east1', '東1ホール'), ('east7', '東7ホール'), ('east6', '東6ホール')], max_length=10)),
                ('assignment_2', models.CharField(choices=[('east8', '東8ホール'), ('east2', '東2ホール'), ('east3', '東3ホール'), ('east4', '東5ホール'), ('east3', '東4ホール'), ('east1', '東1ホール'), ('east7', '東7ホール'), ('east6', '東6ホール')], max_length=10, null=True)),
                ('partner', models.CharField(max_length=64, null=True)),
                ('parking', models.CharField(choices=[('Yes', '使用する'), ('No', '使用しない')], max_length=10)),
                ('hotel', models.CharField(choices=[('Yes', '使用する'), ('No', '使用しない')], max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('memo', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='staff_data',
        ),
    ]
