# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0004_auto_20170828_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdata',
            name='join_day',
        ),
        migrations.AddField(
            model_name='staffdata',
            name='join_day_0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffdata',
            name='join_day_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffdata',
            name='join_day_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffdata',
            name='join_day_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='assignment_1',
            field=models.IntegerField(choices=[(0, '東1ホール'), (1, '東2ホール'), (2, '東3ホール'), (3, '東4ホール'), (4, '東5ホール'), (5, '東6ホール'), (6, '東7ホール'), (7, '東8ホール')], verbose_name=1),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='assignment_2',
            field=models.IntegerField(choices=[(0, '東1ホール'), (1, '東2ホール'), (2, '東3ホール'), (3, '東4ホール'), (4, '東5ホール'), (5, '東6ホール'), (6, '東7ホール'), (7, '東8ホール')], null=True, verbose_name=1),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name=1),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='hotel',
            field=models.IntegerField(choices=[(1, '使用する'), (0, '使用しない')], verbose_name=1),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='parking',
            field=models.IntegerField(choices=[(1, '使用する'), (0, '使用しない')], verbose_name=1),
        ),
    ]
