# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0005_auto_20170828_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('updated_data', models.DateTimeField(auto_now_add=True)),
                ('organization', models.CharField(max_length=20)),
                ('connection', models.TextField(null=True)),
                ('hierarchic_flag', models.IntegerField()),
                ('hole_id', models.IntegerField()),
                ('block_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='assignment_1',
            field=models.IntegerField(choices=[(0, '東1ホール'), (1, '東2ホール'), (2, '東3ホール'), (3, '東4ホール'), (4, '東5ホール'), (5, '東6ホール'), (6, '東7ホール'), (7, '東8ホール')]),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='assignment_2',
            field=models.IntegerField(choices=[(0, '東1ホール'), (1, '東2ホール'), (2, '東3ホール'), (3, '東4ホール'), (4, '東5ホール'), (5, '東6ホール'), (6, '東7ホール'), (7, '東8ホール')], null=True),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='hotel',
            field=models.IntegerField(choices=[(1, '使用する'), (0, '使用しない')]),
        ),
        migrations.AlterField(
            model_name='staffdata',
            name='parking',
            field=models.IntegerField(choices=[(1, '使用する'), (0, '使用しない')]),
        ),
    ]
