# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0007_auto_20170831_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='connection',
            new_name='content',
        ),
        migrations.AddField(
            model_name='information',
            name='carrier_shift',
            field=models.IntegerField(choices=[(0, '雨'), (1, '晴')], default=0),
        ),
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='information',
            name='organization',
            field=models.IntegerField(choices=[(0, '統括部'), (1, '設営部'), (2, '防災防犯'), (3, '販売担当')]),
        ),
    ]
