# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0008_auto_20170831_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='block_id',
        ),
        migrations.RemoveField(
            model_name='information',
            name='hierarchic_flag',
        ),
        migrations.RemoveField(
            model_name='information',
            name='hole_id',
        ),
    ]
