# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0010_auto_20170831_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='updated_data',
        ),
        migrations.AddField(
            model_name='information',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
