# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0011_auto_20170901_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='updated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='carrier_shift',
            field=models.IntegerField(choices=[(0, '雨'), (1, '晴')]),
        ),
    ]
