# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comike', '0012_auto_20170901_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='carrier_shift',
            field=models.IntegerField(choices=[(0, '選択してください'), (1, '晴'), (2, '雨')]),
        ),
    ]
